### ISSUE TITLE
Geographic Information content is empty/invisible after "clear features" is clicked

### ISSUE THREAD

**Issue by kekenes** [kekenes/arcgis_norwayparishes#25]
Set the content when the search is run again.

**Comment by ekenes** [comment]
It should clear `infoContent` instead of `info`.

https://github.com/kekenes/arcgis_norwayparishes/blob/v2.1/JS/parishjs_v2.js#L772

**Comment by kekenes** [comment]
Also add visibility to `toolsContent`

https://github.com/kekenes/arcgis_norwayparishes/blob/v2.1/JS/parishjs_v2.js#L549-L551
